# Generated by Django 4.2.5 on 2023-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_alter_client_date_of_activation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_of_registration",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
