# Generated by Django 4.2.5 on 2023-09-10 12:20

from django.contrib.auth.models import Group
from django.db import migrations


def add_groups(apps, schema_editor):
    groups = ["Admin", "Client"]
    for group in groups:
        _group, _created = Group.objects.get_or_create(name=group)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]
