# Generated by Django 4.2.5 on 2023-09-10 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSubscription",
            fields=[
                (
                    "seq_number",
                    models.PositiveIntegerField(
                        auto_created=True, editable=False, unique=True
                    ),
                ),
                ("date_of_activation", models.DateTimeField()),
                ("date_of_renewal", models.DateTimeField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=69)),
                ("date_of_purchase", models.DateTimeField()),
                (
                    "subscription_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "ref_transaction_number",
                    models.CharField(blank=True, max_length=367, null=True),
                ),
                ("due_date", models.DateTimeField()),
                ("status_term", models.CharField(blank=True, max_length=39, null=True)),
                (
                    "invoice_ref_number",
                    models.CharField(
                        default="INV-REF-63743792", editable=False, max_length=39
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("update_log", models.DateTimeField(auto_now=True)),
                ("is_reconcile", models.BooleanField(default=False)),
                (
                    "transaction_status_term",
                    models.CharField(blank=True, max_length=39, null=True),
                ),
                (
                    "subscription_type_term",
                    models.CharField(blank=True, max_length=39, null=True),
                ),
                ("main_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="client.client",
                    ),
                ),
                (
                    "ref_client_subscription",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subscription.clientsubscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "order_number",
                    models.PositiveIntegerField(
                        auto_created=True, editable=False, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=38, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=38, null=True)),
                ("name", models.CharField(max_length=69)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=361, null=True),
                ),
                ("detail_description", models.TextField()),
                (
                    "subscription_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/images/subscription_images",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("yearly_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionDetail",
            fields=[
                ("is_delete", models.BooleanField(default=False)),
                ("max_competitors", models.PositiveIntegerField(default=0)),
                ("max_corporates", models.PositiveIntegerField(default=0)),
                ("max_properties", models.PositiveIntegerField(default=0)),
                ("max_users", models.PositiveIntegerField(default=0)),
                ("is_marriott_enable", models.BooleanField(default=False)),
                ("is_ihg_enable", models.BooleanField(default=False)),
                ("is_hilton_enable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "upto_corporate_group_term",
                    models.CharField(blank=True, max_length=67, null=True),
                ),
                ("is_enable", models.BooleanField(default=False)),
                ("update_log", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientSubscriptionDetail",
            fields=[
                (
                    "seq_number",
                    models.PositiveIntegerField(
                        auto_created=True, editable=False, unique=True
                    ),
                ),
                ("max_competitors", models.PositiveIntegerField(default=0)),
                ("max_corporates", models.PositiveIntegerField(default=0)),
                ("max_properties", models.PositiveIntegerField(default=0)),
                ("max_users", models.PositiveIntegerField(default=0)),
                ("is_marriott_enable", models.BooleanField(default=False)),
                ("is_ihg_enable", models.BooleanField(default=False)),
                ("is_hilton_enable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("update_log", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actual_competitors", models.PositiveIntegerField(default=0)),
                ("actual_corporates", models.PositiveIntegerField(default=0)),
                ("actual_properties", models.PositiveIntegerField(default=0)),
                ("actual_users", models.PositiveIntegerField(default=0)),
                ("is_ihg_in_use", models.BooleanField(default=False)),
                ("is_marriott_in_use", models.BooleanField(default=False)),
                ("is_hilton_in_use", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="client.client",
                    ),
                ),
                (
                    "client_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subscription.clientsubscription",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="subscription.subscription",
            ),
        ),
    ]
