# Generated by Django 4.2.5 on 2023-11-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="invoice_ref_number",
            field=models.CharField(editable=False, max_length=39),
        ),
    ]
