# Generated by Django 4.2.5 on 2023-11-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_alter_clientsubscription_invoice_ref_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsubscription",
            name="date_of_activation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="date_of_renewal",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
