# Generated by Django 4.2.5 on 2023-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_usruser_association_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usruser",
            name="display_name",
            field=models.CharField(blank=True, max_length=61, null=True),
        ),
    ]
