name: Run Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clear the Python cache
      run: |
        sudo rm -rf /opt/hostedtoolcache/python

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
        architecture: x64

    - name: Set up environment variables
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this to your requirements file name
    - name: Set Django settings module
      run: |
        export DJANGO_SETTINGS_MODULE=rate_shopping.settings
    - name: Run tests
      run: |
        python manage.py test --settings=rate_shopping.settings

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-reports
